name: "@minions-qa-suites/blog"
project_scope: child
child_type: blog
parent_project: minions-qa-suites-workspace
description: "Standard compliance definition for @minions-qa-suites/blog"
priority: high
deploy_url: null
tags: null
